/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/avatar/Avatar.vue')['default']
    Btn: typeof import('./components/btn/Btn.vue')['default']
    ChangeInput: typeof import('./components/user/ChangeInput.vue')['default']
    DisplayCard: typeof import('./components/card/DisplayCard.vue')['default']
    DropZone: typeof import('./components/file/DropZone.vue')['default']
    EmailEditDialog: typeof import('./components/dialog/EmailEditDialog.vue')['default']
    Empty: typeof import('./components/empty/Empty.vue')['default']
    EmptyCloud: typeof import('./components/empty/EmptyCloud.vue')['default']
    EmptyData: typeof import('./components/empty/EmptyData.vue')['default']
    EmptyVeri: typeof import('./components/empty/EmptyVeri.vue')['default']
    NavItem: typeof import('./components/nav/NavItem.vue')['default']
    NavItemSection: typeof import('./components/nav/NavItemSection.vue')['default']
    PasswordInput: typeof import('./components/auth/PasswordInput.vue')['default']
    RectAngleCardSection: typeof import('./components/dialog/RectAngleCardSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderList: typeof import('./components/slider/sliderList.vue')['default']
    SMSInput: typeof import('./components/auth/SMSInput.vue')['default']
    Tree: typeof import('./components/tree/Tree.vue')['default']
    UploadFile: typeof import('./components/file/UploadFile.vue')['default']
    UserCodeInput: typeof import('./components/auth/UserCodeInput.vue')['default']
    VerifyStatus: typeof import('./components/user/VerifyStatus.vue')['default']
    ZDialog: typeof import('./components/dialog/ZDialog.vue')['default']
    ZSelect: typeof import('./components/select/ZSelect.vue')['default']
  }
}
